# Generated by Django 3.0.5 on 2020-04-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firtsapp', '0002_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizzashop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firtsapp.PizzaShop', verbose_name='Пиццерия'),
        ),
    ]
