# Generated by Django 3.0.5 on 2020-04-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firtsapp', '0004_auto_20200413_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name'], 'verbose_name': 'Пицца', 'verbose_name_plural': 'Пиццы'},
        ),
    ]
